### ISSUE TITLE
瀏覽器窗口高度比較小的情況下，對話框的顯示不全

### ISSUE THREAD

**Issue by black-black-cat** [Knovour/food#1]
![default](https://user-images.githubusercontent.com/15521864/35468577-05de470e-035c-11e8-86ed-d1f1a41a0f0f.png)

Hey, buddy!

如上圖，對話框的下邊部分看不見了。我的瀏覽器窗口尺寸是：1280 * 599

**Comment by Knovour** [comment]
真的有人在用喔...

**Comment by Knovour** [comment]
@black-black-cat 再試試看
![www harvest moe_](https://user-images.githubusercontent.com/893846/35470371-6f2f0fb4-0383-11e8-98d0-7c748c530f9b.png)

**Comment by black-black-cat** [comment]
可以了。Nice！
